### ISSUE TITLE
Resultset already closed

### ISSUE THREAD

**Issue by PaulZH** [ontop/ontop#254] opened 2018-03-02 08:58 UTC
### Description

When changing the SQL query within the Mapping editor, New Mapping, I get the resultset is already closed, when changing the SQL query
<img width="1542" alt="screen shot 2018-03-02 at 09 53 43" src="https://user-images.githubusercontent.com/437781/36890952-2d6e190c-1e00-11e8-93d8-c5f37ecea65c.png">

### Steps to Reproduce
Having an established JDBC connection with Dremio.

1. Mapping editor
2. New Mapping
3. Enter SQL query
e.g.
SELECT ID
FROM "@PaulZH".aantal_woningen

Query returns results

4. Change SQL query
e.g.
SELECT *
FROM "@PaulZH".aantal_woningen

Then getting error message as included.

**Reproduces how often:** [Does it happen every time?]
Yes

### Attached material

Error message.

Informations about the attachments (ontology, mappings and queries that are necessary to reproduce the problem)
Provide the log file (more information on how to obtain it in the guidelines)

### Versions

Latest, downloaded this morning.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by skomlaebri** [comment] 2018-03-02 13:52
I can reproduce this issue with JDBC dremio driver. The problem appears everytime the source query is tested more than once. It can be retested once closing the new mapping tab and rediting the mapping source in the edit mapping tab. We will have a look at the problem.

**Comment by bcogrel** [comment] 2018-03-02 16:49
Hi,
This message appears because the JDBC dremio driver is forced by Calcite Avatica to throw a runtime exception instead of a SQLException when one tries to access an already closed statement.

We are fixing the inappropriate call on our side and we reported the issue to Calcite Avatica:
https://issues.apache.org/jira/browse/CALCITE-2199

**Closed** 2018-03-02 17:12 UTC
Labels: status: fixed, topic: protégé, type: defect, w: db support
