### ISSUE TITLE
ERROR: Failure while attempting to cast value '' to Integer.

### ISSUE THREAD

**Issue by seralf** [ontop/ontop#334] opened 2020-05-14 23:19 UTC
### Description

An SQL query with two conditions on Integer field in WHERE gives an ERROR that seems related to a cast to string

### Steps to Reproduce

execute an example using a query similar to the following one:

```
SELECT {some_field}, ANNO, MESE 
FROM {my_table}
WHERE( 
	ANNO = 2020 AND MESE = 4 
)
LIMIT 10
```

where the fields ANNO and MESE are integers

**Expected behavior:** 
I expected a result or -in the worst scenario- no results. I don't expect an error.

**Actual behavior:** 
The run gives the error:

```
[Error Id: 613b12f7-fac9-40d2-86ec-5fd1dbc4ad07 on b1757aad3efe:31010]
        at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer$GraphMaterializationIteration.hasNext(DefaultRDF4JMaterializer.java:242)
        at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:67)
        at it.unibz.inf.ontop.cli.OntopMaterialize.serializeTripleBatch(OntopMaterialize.java:258)
        at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:168)
        ... 2 more
Caused by: it.unibz.inf.ontop.exception.OntopQueryEvaluationException: FUNCTION ERROR: Failure while attempting to cast value '' to Integer.

SqlOperatorImpl FILTER
Location 1:0:15
Fragment 1:0
...

```

**Reproduces how often:** 

The error is returned every time with this type of query.

### Attached material

N/A

### Versions

version 3.0.0

### Additional Information

N/A

**Comment by juliencorman** [comment] 2020-05-24 15:52
Hello Alfredo,

This looks like a bug.
In order to reproduce it, we may need extra information.
Could you precise which source DBMS you are using, an share the mapping (or at least the mapping targets that use <some_field>, ANNO and MESE)? 

Thank you,
Julien

**Comment by bcogrel** [comment] 2021-03-03 11:10
The parts involved have been significantly refactored since 3.0. I am closing the issue for now, but if the problem still persists with 4.1, feel free to re-open the issue.

**Closed by bcogrel** 2021-03-03 11:10 UTC
