### ISSUE TITLE
SPARQLQueryUtility's method getSelectFromConstruct does not handle properly comments with CONSTRUCT or WHERE in them

### ISSUE THREAD

**Issue by sava-savov-ontotext** [ontop/ontop#362] opened 2020-10-16 07:57 UTC
Converting CONSTRUCT query with comments, that have CONSTRUCT or WHERE in them returns strange query for execution.

### Steps to Reproduce

1. Execute query:

```
# CONSTRUCT or DESCRIBE query. 
CONSTRUCT WHERE {
	?s ?p ?o
} LIMIT 10
```

**Expected behavior:** Should return result

**Actual behavior:** 

java.lang.IllegalStateException: Bug: bad extraction of the SELECT query from a CONSTRUCT query :Encountered " <VAR1> "?s "" at line 2, column 2.
Was expecting one of:
    "base" ...
    "prefix" ...
    "select" ...
    "construct" ...
    "describe" ...
    "ask" ...
    
	at it.unibz.inf.ontop.answering.reformulation.input.impl.RDF4JConstructQuery.extractSelectParsedQuery(RDF4JConstructQuery.java:27)
	at it.unibz.inf.ontop.answering.reformulation.input.impl.RDF4JConstructQuery.<init>(RDF4JConstructQuery.java:17)
	at it.unibz.inf.ontop.answering.reformulation.input.impl.RDF4JInputQueryFactoryImpl.createConstructQuery(RDF4JInputQueryFactoryImpl.java:26)
	at it.unibz.inf.ontop.rdf4j.query.impl.OntopGraphQuery.evaluate(OntopGraphQuery.java:56)

**Reproduces how often:** Always

### Versions

Latest released

**Comment by bcogrel** [comment] 2020-10-18 11:18
Hi,

I didn't manage to reproduce the problem with 4.0.3 and a snapshot version of 4.1 (see https://sparql.opendatahub.bz.it/#query=CONSTRUCT+WHERE+%7B%0A%09%3Fs+%3Fp+%3Fo%0A%7D+LIMIT+10&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fsparql.opendatahub.testingmachine.eu%2Fsparql&requestMethod=POST&tabTitle=Query+11&headers=%7B%7D&outputFormat=rawResponse).

I suspect this problem may have been fixed by https://github.com/ontop/ontop/commit/20a28d9755c297e61b09842660f0a88acb519ee1 , which has been releasing with 4.0.0-rc1 .

Which version are you using?

Best,
Benjamin

**Comment by ghxiao** [comment] 2020-10-18 12:39
Hi @bcogrel 

The problem is the comment `# CONSTRUCT or DESCRIBE query. ` at the beginning of the query:

Try the following link and we can reproduce the issue:

https://sparql.opendatahub.bz.it/#query=%23+CONSTRUCT+or+DESCRIBE+query.+%0ACONSTRUCT+WHERE+%7B%0A%09%3Fs+%3Fp+%3Fo%0A%7D+LIMIT+10&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fsparql.opendatahub.testingmachine.eu%2Fsparql&requestMethod=POST&tabTitle=Query+11&headers=%7B%7D&outputFormat=error

Best,

Guohui

**Comment by sava-savov-ontotext** [comment] 2020-10-18 16:43
Hi Benjamin,

Comments, containing CONSTRUCT or where in them won't be converted properly
to SELECT query, which code should do. Put one of those in comment and see
the result.

Regards,
Sava

**Comment by bcogrel** [comment] 2020-10-18 18:37
Thanks Guohui and Sava,

Sorry, indeed I missed the point that this test was about the comment line, my bad.

This comment line is a good example against the approach of decomposing the CONSTRUCT and the WHERE blocks using the query string instead of the parsed tree.

One would have to refactor that part. It should also be more efficient, as it would save Ontop from re-parsing the WHERE block. 

It could also be the occasion to detect which variables are needed by the CONSTRUCT block instead of projecting all the variables. This would enable further optimization.

Sava, in your experience, how sensitive is that issue? Does it break a fair amount of queries?

Best,
Benjamin

**Comment by sava-savov-ontotext** [comment] 2020-10-19 05:46
Hi Benjamin,

As soon as one finds what is the issue the problem is miner. My workaround
in our application to remove all comments that are sent to the Ontop
repository. I'll suggest fix soon if possible.

Regards
Sava

**Comment by bcogrel** [comment] 2021-01-27 17:44
Hi,

We finally got rid of our old code for separating the CONSTRUCT and WHERE blocks (https://github.com/ontop/ontop/commit/c9a06a3e5ce038a775e2237f5c696deb41e54719). 
It was also causing problems for CONSTRUCT queries not using the WHERE keyword.

Thanks again for reporting the issue!

Best,
Benjamin

**Closed by bcogrel** 2021-01-27 17:44 UTC
Labels: status: accepted, type: defect
