### ISSUE TITLE
SQL queries ending with ; produce obda files that can't be read by ontop cli.

### ISSUE THREAD

**Issue by bjonnh** [ontop/ontop#275] opened 2018-10-11 20:21 UTC
### Description

SQL queries cannot end by ;

### Steps to Reproduce

1. In protege, add a query that ends with ; in a mapping
2. Use the generated OBDA file into ontop CLI

**Expected behavior:** Correct materialization

**Actual behavior:** Ontop CLI fails with an error

**Reproduces how often:** Everytime

Removing the ; at the end of the query solves the problem.

### Attached material

Oct 11, 2018 3:19:12 PM org.apache.tomcat.jdbc.pool.PooledConnection connectUsingDriver
WARNING: Not loading a JDBC driver as driverClassName property is null.
Oct 11, 2018 3:19:12 PM org.apache.tomcat.jdbc.pool.PooledConnection connectUsingDriver
WARNING: Not loading a JDBC driver as driverClassName property is null.
15:19:12.411 |-ERROR in i.u.i.o.a.c.impl.QuestStatement - ERROR: syntax error at or near ";"
  Position: 1440
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: ERROR: syntax error at or near ";"
  Position: 1440
	at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeGraphQuery(SQLQuestStatement.java:222) ~[ontop-system-sql-core-3.0.0-beta-2.jar:3.0.0-beta-2]
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeConstructQuery(QuestStatement.java:173) ~[ontop-system-core-3.0.0-beta-2.jar:3.0.0-beta-2]
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement$QueryExecutionThread.run(QuestStatement.java:130) ~[ontop-system-core-3.0.0-beta-2.jar:3.0.0-beta-2]
15:19:12.416 |-ERROR in i.u.i.o.m.i.DefaultOntopRDFMaterializer$DefaultMaterializedGraphResultSet - Problem materialiing the class/property it.unibz.inf.ontop.materialization.impl.DefaultOntopRDFMaterializer$VocabularyEntry@1dbd580
Error materializing ontology:
it.unibz.inf.ontop.owlapi.exception.OntopOWLException: it.unibz.inf.ontop.exception.OntopQueryEvaluationException: ERROR: syntax error at or near ";"
  Position: 1440
	at it.unibz.inf.ontop.owlapi.resultset.impl.OntopGraphOWLResultSet.hasNext(OntopGraphOWLResultSet.java:29)
	at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:328)
	at it.unibz.inf.ontop.cli.OntopMaterialize.run(OntopMaterialize.java:97)
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:18)
Caused by: it.unibz.inf.ontop.exception.OntopQueryEvaluationException: ERROR: syntax error at or near ";"
  Position: 1440
	at it.unibz.inf.ontop.answering.connection.impl.SQLQuestStatement.executeGraphQuery(SQLQuestStatement.java:222)
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement.executeConstructQuery(QuestStatement.java:173)
	at it.unibz.inf.ontop.answering.connection.impl.QuestStatement$QueryExecutionThread.run(QuestStatement.java:130)

### Versions

Last Ontop (git master) , last Protege plugin (git master), last protege (git master)

**Comment by ghxiao** [comment] 2020-07-06 21:09
Hi,

We are not able to reproduce the problem with the latest version of Ontop. It is likely the issue has been addressed in the meanwhile.

Feel free to reopen the issue if the problem persists.

**Closed by ghxiao** 2020-07-06 21:09 UTC
