### ISSUE TITLE
The substr function does not work with xsd:integer parameters if PostgreSQL is used

### ISSUE THREAD

**Issue by galgonek** [ontop/ontop#545] opened 2022-08-05 14:01 UTC
### Description

In PostgreSQL, the substr function supports only integer parameters to specify the start position and the length. However, in some cases, Ontop generates SQL queries that use values of other numeric types (e.g., bigint) in this function.

### Steps to Reproduce

If the following database is created in PostgreSQL:
```sql
create table test (id integer, value bigint, primary key(id));
insert into test values (1, 1);
```
and if the following mapping is used
```
[PrefixDeclaration]
rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
ex: http://example.org/
[MappingDeclaration] @collection [[
mappingId  map001
target     ex:{id} rdf:value {value}^^xsd:integer.
source     select * from test
]]
```
then the SPARQL query
```sparql
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
select (substr("test", ?O) as ?R) where {
  ?S rdf:value ?O
}
```
returns the following error:
```
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: org.postgresql.util.PSQLException: ERROR: function substr(unknown, bigint) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8
```

### Versions

Ontop endpoint 4.2.1

**Comment by bcogrel** [comment] 2022-09-16 13:49
Hi @galgonek, thanks for reporting it!

Note to myself: I managed to reproduce the issue with a query not involving any mapping:
```sparql
SELECT * WHERE {
  {
    SELECT DISTINCT ?b {
      {
        SELECT * {
          VALUES ?b { 2 }
        }
      }
      UNION {
        SELECT * {
          VALUES ?b { "aa" }
        }
      }
    }
  }
  BIND (SUBSTR("yyy", ?b) AS ?v)
}
```

**Comment by bcogrel** [comment] 2022-09-16 19:27
For the SPARQL query I proposed, Ontop generates: 
```sql
SELECT v6."v0" AS "v0", CASE WHEN v6."v2" <> 1 THEN SUBSTR('yyy',CAST(v6."v0" AS BIGINT)) ELSE NULL END AS "v1", v6."v2" AS "v2"
FROM (SELECT DISTINCT v4."v0" AS "v0", v4."v2" AS "v2"
FROM (SELECT '2' AS "v0", 0 AS "v2"
FROM (SELECT 1 ) tdummy
UNION ALL 
SELECT 'aa' AS "v0", 1 AS "v2"
FROM (SELECT 1 ) tdummy
UNION ALL 
SELECT 'aa' AS "v0", 1 AS "v2"
FROM (SELECT 1 ) tdummy
) v4
) v6
```

It is `CAST(v6."v0" AS BIGINT)` that makes the query fail, because PostgreSQL expects an int4 (integer), not an int8 (bigint)…

At the moment, we don't have a mechanism to cast a column to a preferred datatype of a specific function. That's the first case of the kind experienced so far.

**Comment by bcogrel** [comment] 2022-09-17 09:19
Actually I found a simple solution: https://github.com/ontop/ontop/commit/d7e3b0c2d747eacb47ddbfb466df7c14634a1fce .

It is now fixed. Thanks again for reporting!

**Closed by bcogrel** 2022-09-17 09:19 UTC
Labels: type: defect, status: accepted, w: sparql function
