### ISSUE TITLE
 Annotation properties assigned with untyped literals or unsupported datatypes produce RuntimeException error 

### ISSUE THREAD

**Issue by tarcisiotmf** [ontop/ontop#316] opened 2019-11-27 16:53 UTC
### Description

Any annotation property stated with a non explicit type gets an "unknown typeCode -1", e.g. (ex:URI rdfs:label "bla bla" ). This happens when trying to materialise triples with Ontop-cli-3.0.0 and considering an ontology file with untyped values or types not defined in "java enum COL_TYPE"  such as xsd:anyURI . Personally, I think that is more critical to support untyped values that should be considered for example as xsd:string (see https://www.w3.org/TR/rdf11-concepts/#dfn-simple-literal). In other words, to support simple literals. 

 
### Steps to Reproduce

1. Create any ontology with simple literals such as (ex:SimpleLiteral rdfs:label **"test"**)
2. Give it as an input of the Ontop materialize CLI tool

**Expected behavior:** 
Keeping the annotation property triples from the original ontology file.
 
**Actual behavior:** [What actually happens]
Runtime exception

java.lang.RuntimeException: org.eclipse.rdf4j.query.QueryEvaluationException: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.exception.OntopResultConversionException: typeCode unknown: -1
	at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:175)
	at it.unibz.inf.ontop.cli.OntopMaterialize.run(OntopMaterialize.java:124)
	at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:18)
	at org.bgee.rdf.converter.Test.main(Test.java:14)
Caused by: org.eclipse.rdf4j.query.QueryEvaluationException: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.exception.OntopResultConversionException: typeCode unknown: -1
	at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer$GraphMaterializationIteration.hasNext(DefaultRDF4JMaterializer.java:242)
	at org.eclipse.rdf4j.common.iteration.IterationWrapper.hasNext(IterationWrapper.java:67)
	at it.unibz.inf.ontop.cli.OntopMaterialize.serializeTripleBatch(OntopMaterialize.java:258)
	at it.unibz.inf.ontop.cli.OntopMaterialize.runWithSingleFile(OntopMaterialize.java:168)
	... 3 more
Caused by: it.unibz.inf.ontop.exception.OntopResultConversionException: it.unibz.inf.ontop.exception.OntopResultConversionException: typeCode unknown: -1
	at it.unibz.inf.ontop.answering.resultset.impl.JDBC2ConstantConverter.getConstantFromJDBC(JDBC2ConstantConverter.java:246)
	at it.unibz.inf.ontop.answering.resultset.impl.DelegatedIriSQLBindingSet.getConstant(DelegatedIriSQLBindingSet.java:56)
	at it.unibz.inf.ontop.answering.resultset.impl.DelegatedIriSQLBindingSet.getConstant(DelegatedIriSQLBindingSet.java:66)
	at it.unibz.inf.ontop.answering.resultset.impl.DefaultSimpleGraphResultSet.getConstant(DefaultSimpleGraphResultSet.java:206)
	at it.unibz.inf.ontop.answering.resultset.impl.DefaultSimpleGraphResultSet.processResults(DefaultSimpleGraphResultSet.java:119)
	at it.unibz.inf.ontop.answering.resultset.impl.DefaultSimpleGraphResultSet.hasNext(DefaultSimpleGraphResultSet.java:164)
	at it.unibz.inf.ontop.materialization.impl.DefaultOntopRDFMaterializer$DefaultMaterializedGraphResultSet.hasNext(DefaultOntopRDFMaterializer.java:217)
	at it.unibz.inf.ontop.rdf4j.materialization.impl.DefaultRDF4JMaterializer$GraphMaterializationIteration.hasNext(DefaultRDF4JMaterializer.java:240)
	... 6 more
Caused by: it.unibz.inf.ontop.exception.OntopResultConversionException: typeCode unknown: -1
	at it.unibz.inf.ontop.answering.resultset.impl.JDBC2ConstantConverter.getConstantFromJDBC(JDBC2ConstantConverter.java:136)
**Reproduces how often:** [Does it happen every time?]

### Versions

Ontop CLI 3.0.0
materialize command 
### Additional Information

After removing the simple literals (untyped values) the materialisation works well.

**Comment by ghxiao** [comment] 2020-07-06 20:55
Hi, this issue should have been fixed already in version 4, after a major refactoring of type handling in Ontop. We could not reproduce it. 

I close this issue, but please do feel free to reopen it if the issue persists with Ontop v4.

**Closed by ghxiao** 2020-07-06 20:55 UTC
