### ISSUE TITLE
iriSafeEncoding problem in the Protege plugin.

### ISSUE THREAD

**Issue by elemguzel** [ontop/ontop#264] opened 2018-05-25 13:31 UTC
Disabling iri safe encoding inside the properties file does not work with the Protege plugin, while it works when i run a unit test inside the code. 
In addition, enabling iri safe encoding causes exceptions on connecting Redshift through ontop.

**Comment by bcogrel** [comment] 2018-09-10 11:32
Could not reproduce the problem, it seems to work.
Closing for now, feel free to re-open the issue if you manage to reproduce it.

**Closed by bcogrel** 2018-09-10 11:32 UTC
Labels: status: under analysis, topic: protégé, type: defect
