### ISSUE TITLE
Make columns field optional in lenses

### ISSUE THREAD

**Issue by tirrolo** [ontop/ontop#592] opened 2023-01-31 13:02 UTC
### Description

Whenever a lens without a columns object is declared, ontop breaks with a NullPointerException 

### Steps to Reproduce

Provide a BasicLens without a columns object

**Expected behavior:** [What you expect to see]

Ontop runs normally

**Actual behavior:** [What actually happens]

Ontop throws a NullPointerException

**Reproduces how often:** [Does it happen every time?]

Always

### Versions

version5 branch

**Comment by tirrolo** [comment] 2023-01-31 13:11
Bug fixed in branch bugfix/lenses-make-columns-optional.

Added unit test LensesNoColumnsTest (depending on a docker postgres DB on obdalin). Probably such test should be ported in docker-test in the future.

Please, merge in version5.

**Comment by bcogrel** [comment] 2023-02-02 21:04
Hi @tirrolo, thanks for the fix. 

However, the test `LensNoColumnsTest` cannot be merged, because it is is a module (`ontop-rdf4j`) that should not depend on an external server. This server is also not publicly available so it breaks the Github CI: https://github.com/ontop/ontop/actions/runs/4078538450/jobs/7028869670

I suggest reimplementing the test with H2 and a minimalist setting, so as to make easily portable.

**Comment by bcogrel** [comment] 2023-02-24 18:11
I reproduced the issue by adapting an existing test and created a commit for your fix:  https://github.com/ontop/ontop/commit/ac4c7bab00751bda00dd42fdbd6db99bbf447278.

It will take part of 5.0.2 and is already in the branch `releasing/v5.0` and `version5`.

Thanks again!

**Closed by bcogrel** 2023-02-24 18:11 UTC
