### ISSUE TITLE
Mapping generation fails on MySQL due to "unknown table"

### ISSUE THREAD

**Issue by namedgraph** [ontop/ontop#270] opened 2018-09-12 13:50 UTC
### Description

Mapping bootstrapping fails on different MySQL DBs

### Steps to Reproduce

Run the following command: `./ontop bootstrap -p $ONTOP_JDBC_PROPERTIES -m $ONTOP_MAPPING -t $ONTOP_ONTOLOGY -b $ONTOP_BASE_IRI`

**Expected behavior:** Mapping is generated successfully

**Actual behavior:** Mapping generation fails

**Reproduces how often:** All the time with the same specific MySQL DBs

### Attached material

```it.unibz.inf.ontop.exception.MappingBootstrappingException: java.sql.SQLSyntaxErrorException: Unknown table 'action_rules' in information_schema
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DirectMappingEngine.bootstrapMappingAndOntology(DirectMappingEngine.java:136)
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DirectMappingEngine.bootstrap(DirectMappingEngine.java:97)
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DefaultDirectMappingBootstrapper.bootstrap(DefaultDirectMappingBootstrapper.java:16)
        at it.unibz.inf.ontop.cli.OntopBootstrap.run(OntopBootstrap.java:40)
        at it.unibz.inf.ontop.cli.Ontop.main(Ontop.java:18)
Caused by: java.sql.SQLSyntaxErrorException: Unknown table '*******' in information_schema
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1218)
        at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:2965)
        at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:2953)
        at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56)
        at com.mysql.cj.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3006)
        at it.unibz.inf.ontop.dbschema.RDBMetadataExtractionTools.getPrimaryKey(RDBMetadataExtractionTools.java:557)
        at it.unibz.inf.ontop.dbschema.RDBMetadataExtractionTools.loadMetadata(RDBMetadataExtractionTools.java:274)
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DirectMappingEngine.bootstrapMappings(DirectMappingEngine.java:212)
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DirectMappingEngine.extractPPMapping(DirectMappingEngine.java:194)
        at it.unibz.inf.ontop.spec.mapping.bootstrap.impl.DirectMappingEngine.bootstrapMappingAndOntology(DirectMappingEngine.java:120)
        ... 4 more
```

### Versions

Version 3 beta as Docker image: https://github.com/AtomGraph/ontop/tree/version3-docker/docker

### Additional Information

Happens with 2 different MySQL databases, both on MySQL 5.7.23 and MySQL 5.7.19.

**Comment by ghxiao** [comment] 2018-09-12 14:39
Hi @namedgraph ,

I quickly tested the latest v3-beta-3-SNAPSHOT, but I could not reproduces the problem on the MySQL database (5.7.23-0ubuntu0.16.04.1) that we are using for testing.

Reading your logs, it appears the problem happens when retrieving the primary keys from the databases. The error message "Unknown table '*******' in information_schema" suggests that it seems that the JDBC driver is not able to find the metadata of the table '*******'. 

In order to solve your issue, we need a way to reproduce the problem. Without any data, we are not able to analyze and debug the issue. Maybe you can share a minimal dump of your schemas?

**Comment by namedgraph** [comment] 2018-09-13 09:39
@ghxiao did it help?

**Comment by ghxiao** [comment] 2018-09-13 10:33
It appears to be a problem of versions of JDBC drivers.

In your docker, mysql-connector-java-8.0.12.jar is used and I can reproduce the problem.

With an older version of mysql-connector-java-5.1.46.jar, I don't have such issue.

I will investigate further.

**Comment by namedgraph** [comment] 2018-09-15 08:49
Any solution in sight? :)

**Comment by ghxiao** [comment] 2018-09-15 11:48
We have confirmed that the problem is that MySQL-connector drivers v5.x and v8.x have different behaviors when retrieving metadata. We are working on a hotfix now. 

In the meanwhile, you can just use MySQL-connector driver v5.

**Comment by ghxiao** [comment] 2018-09-19 08:47
Hi, we have worked out a hotfix of supporting MySQL connector v8 in https://github.com/ontop/ontop/commit/f5eebb225b3a3da50745fb07c55c274a41e8cd68. Now ontop should work with both v5 and v8. 

The fix has been merged to the version3 branch. Please give it a try.

**Closed** 2019-01-08 17:22 UTC
Labels: status: fixed, topic: bootstrapping
