### ISSUE TITLE
Wrong ID when creating new repository in rdf4j-workbench

### ISSUE THREAD

**Issue by daghovland** [ontop/ontop#207] opened 2017-09-15 07:14 UTC
With rdf4j-workbench, when making a new repository, there is a minor inconvenience in the setup, which may lead to errors if not resolved by the end user.

The "id" that is chosen in the first window is not passed on to the second window. Instead "ontop-virtual" is set as the id. 

This is the first screen in the repo setup
![skjermbilde fra 2017-09-15 09-09-53](https://user-images.githubusercontent.com/444395/30470668-e9104782-99f5-11e7-85eb-0db1a84310f3.png)

This is the second screen. As you see, the id is not the one from the previous, but rather "ontop-virtual"
![skjermbilde fra 2017-09-15 09-10-17](https://user-images.githubusercontent.com/444395/30470662-e72ae116-99f5-11e7-84c5-53068818ef3a.png)

**Comment by bcogrel** [comment] 2018-09-10 09:38
Hi, I have just tried to reproduce the problem in the version3 branch, but I didn't succeed. 
So I guess the problem is gone but perhaps it is a platform-specific issue that you might be able to reproduce.

I am closing the issue for now, but feel free to re-open it if the problem didn't disappear in your setting.

**Closed by bcogrel** 2018-09-10 09:38 UTC
Labels: topic: deployment, topic: rdf4j
